# toolchains
CLANG   := clang
BPFTOOL := bpftool
CC      := gcc

# project roots / dirs
PROJECT_ROOT := $(shell pwd)

# source directories
EXPORTER_DIR    := metrics/exporter
ENV_DIR         := environment
MODEL_DIR       := model
IMPORTER_DIR 	:= metrics/importer

# sources / headers
BPF_PROG        := ebpf_jagent.bpf.c
BPF_OBJ         := ebpf_jagent.bpf.o
USER_PROG       := ebpf_jagent.user.c
EXPORTER_SRC    := $(EXPORTER_DIR)/metrics_exporter.c
EXPORTER_HDR    := $(EXPORTER_DIR)/metrics_exporter.h
EVENT_HDR       := $(MODEL_DIR)/event.h
ENV_LOADER_SRC  := $(ENV_DIR)/env_loader.c
ENV_LOADER_HDR  := $(ENV_DIR)/env_loader.h
PROCESS_CPU_SRC := $(IMPORTER_DIR)/process_cpu.c
PROCESS_CPU_HDR := $(IMPORTER_DIR)/process_cpu.h

USER_BIN := ebpf-jagent
SKELETON := ebpf_jagent.skel.h

# kernel headers for BPF compile
KERNEL_SRC ?= /usr/src/linux-headers-$(shell uname -r)

# flags
CFLAGS     := -O2 -g -Wall -MMD -MP \
              -I$(EXPORTER_DIR) -I$(MODEL_DIR) -I$(ENV_DIR) -I$(IMPORTER_DIR) -I$(PROJECT_ROOT)
# Compiling with `-target bpf` drops the host include paths, so the <asm/*.h>
# headers that bpf/usdt.bpf.h reaches via <linux/errno.h> are not found. On
# Debian/Ubuntu they live in the multiarch directory; adding it here avoids
# having to symlink asm-generic into /usr/include, as the Dockerfile does.
ARCH_TRIPLET := $(shell dpkg-architecture -qDEB_HOST_MULTIARCH 2>/dev/null || echo $(shell uname -m)-linux-gnu)

BPF_CFLAGS := -target bpf -D__TARGET_ARCH_x86 \
              -I$(KERNEL_SRC)/include/uapi \
              -I$(KERNEL_SRC)/include \
              -I$(KERNEL_SRC)/arch/x86/include/uapi \
              -I$(KERNEL_SRC)/arch/x86/include \
              -I/usr/include/$(ARCH_TRIPLET) \
              -I.

LDFLAGS := -lbpf -lelf -lz -lcurl

# object files (userland)
USER_OBJS := \
	ebpf_jagent.user.o \
	$(EXPORTER_DIR)/metrics_exporter.o \
	$(ENV_DIR)/env_loader.o \
	$(IMPORTER_DIR)/process_cpu.o

# phony targets
.PHONY: all clean distclean

# default
all: $(USER_BIN)

# Build BPF object
$(BPF_OBJ): $(BPF_PROG)
	@echo "Compiling BPF program..."
	$(CLANG) $(CFLAGS) $(BPF_CFLAGS) -c $< -o $@

# Regenerate skeleton if bpftool is available
$(SKELETON): $(BPF_OBJ)
	@if command -v $(BPFTOOL) >/dev/null 2>&1; then \
	  echo "⟳ Generating BPF skeleton…"; \
	  if $(BPFTOOL) gen skeleton $< > $@; then \
	    echo "✅ Skeleton updated"; \
	  else \
	    echo "⚠️ bpftool failed; keeping old $@"; \
	  fi \
	else \
	  echo "⚠️ bpftool not found; skipping skeleton generation"; \
	fi

# Generic rule: compile .c to .o with dependency on headers and skeleton
%.o: %.c $(EXPORTER_HDR) $(EVENT_HDR) $(ENV_LOADER_HDR) $(PROCESS_CPU_HDR) $(SKELETON)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Special-case compiling env_loader and process_cpu (they don't depend on all other headers)
$(ENV_DIR)/env_loader.o: $(ENV_LOADER_SRC) $(ENV_LOADER_HDR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(IMPORTER_DIR)/process_cpu.o: $(PROCESS_CPU_SRC) $(PROCESS_CPU_HDR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

ebpf_jagent.user.o: $(USER_PROG) $(EXPORTER_HDR) $(EVENT_HDR) $(ENV_LOADER_HDR) $(PROCESS_CPU_HDR) $(SKELETON)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(EXPORTER_DIR)/metrics_exporter.o: $(EXPORTER_SRC) $(EXPORTER_HDR) $(EVENT_HDR) $(ENV_LOADER_HDR) $(PROCESS_CPU_HDR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Link final binary
$(USER_BIN): $(USER_OBJS) $(SKELETON)
	@echo "Linking userland binary..."
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

# Include autogenerated dependency files if present (don't error if missing)
-include $(USER_OBJS:.o=.d)

clean:
	rm -f $(BPF_OBJ) $(USER_BIN) $(USER_OBJS) *.d
	@if command -v $(BPFTOOL) >/dev/null 2>&1; then \
	  rm -f $(SKELETON); \
	else \
	  echo "⚠️ bpftool not found; skipping skeleton cleanup"; \
	fi

distclean: clean
